# Settings
baseurl = "http://homo.run/"
languageCode = "zh-CN"
title = "Zanxinz ç›¸å†Œ"
theme = "autophugo"



#googleAnalytics = ""
disableKinds = ["taxonomy", "term"]
[taxonomies]
    tag = "tags"
    category = "categories"

[Author]
    name = "ZanxinZ"
    email = "ZanxinZ@outlook.com"

[params]
    # Meta
    description = "AutoPhugo - Photo Gallery on Hugo"
    keywords = "phugo, hugo, photogallery, photoblog, hugo theme"
    #msvalidate = ""
    #googlesiteverification = ""
    #thumb_width = 480
    #thumb_quality = 50
    #full_width = 960
    #full_quality = 100
    column_count = 4
    breadcrumb_use_title = false
    #filename_as_phototitle = false
    images_downloadable = true
    images_downloadable_use_orig = true # åŸå›¾ä¸‹è½½
    taxonomies_links = false

    # Headerbar links
    # Do not put too many links here,
    # it will break mobile appearance

    [[params.header.links]]
    name = "å…³äº"
    url = "#footer"
    icon = "fa-info-circle"

    # Footer panel

    [params.footer.paragraph]
    headline = "ç½‘ç«™ä»‹ç»"
    text = """\
    Hi ğŸ‘‹ æˆ‘æ˜¯ ZanxinZï¼Œä¸€ä¸ªå¶å°”ä¼šæ‘„å½±è®°å½•ç”Ÿæ´»çš„äººã€‚ \
    æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç©ºé—´ï¼Œè¿™é‡Œå­˜æ”¾ç€å„ç§ç”Ÿæ´»ç¢ç‰‡ã€‚ \
    """

    [params.footer.social]
    headline = "ç¤¾äº¤"

    [[params.footer.social.links]]
    label = "Twitter"
    url = "#"
    icon = "fa-twitter"



    #[[params.footer.social.links]]
    #label = "Instagram"
    #url = "#"
    #icon = "fa-instagram"

    [[params.footer.social.links]]
    label = "Github"
    url = "https://github.com/ZanxinZ"
    icon = "fa-github"

    [[params.footer.social.links]]
    label = "Site"
    url = "https://github.com/ZanxinZ"
    icon = "/img/favicon.ico"

    # Contact form


    [params.footer.contact]
    hide = true # Set this to true if you don't want to have a contact form on your site
    formspreeID = "myuniqueID" # Getting value from Formspree integration endpoint (eg. https://formspree.io/f/myuniqueID)
    headline = "è”ç³»æˆ‘"
    buttonText = "Send"
    resetText = "Reset"

    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"

    # Copyright
    [params.footer.copyright]
    name = "ZanxinZ"
